### ISSUE TITLE
Support for Wandering Trader's Void Trading

### ISSUE THREAD

**Issue by Young912** [sebseb7/autotrade-fabric#2]
As the previous friend mentioned about the request for void trading, I hope you can add a function for continuous trading by wandering traders. Thank you very much and wish you have a nice Christmas.

**Comment by sebseb7** [comment]
it there a tutorial video for wandering void trading?

**Comment by Young912** [comment]
> it there a tutorial video for wandering void trading?

Just like the working principle of void trading, it's just replacing villagers with wandering traders. Because when I was using this mod, it seemed that the mod could not recognize the wandering traders.

**Comment by sebseb7** [comment]
I will have a look at it ... should be doable.

**Comment by Young912** [comment]
> I will have a look at it ... should be doable.

Thank you very much!

**Comment by sebseb7** [comment]
do you have a world download for this?

**Comment by Young912** [comment]
> do you have a world download for this?

Wait, give me a second

**Comment by sebseb7** [comment]
can you test this dev build?

https://github.com/sebseb7/autotrade-fabric/actions/runs/7326365773

**Comment by Young912** [comment]
> can you test this dev build?
> 
> https://github.com/sebseb7/autotrade-fabric/actions/runs/7326365773

This is working, could you please make a version of 1.20.1

**Comment by Young912** [comment]
> > can you test this dev build?
> > https://github.com/sebseb7/autotrade-fabric/actions/runs/7326365773
> 
> It is working now, could you please make a version of 1.20.1?

**Comment by Young912** [comment]
> can you test this dev build?
> 
> https://github.com/sebseb7/autotrade-fabric/actions/runs/7326365773

It is working in 1.20.4 now, but it is incompatible with other versions. Could you please make other versions like that?

**Comment by sebseb7** [comment]
> > can you test this dev build?
> > https://github.com/sebseb7/autotrade-fabric/actions/runs/7326365773
> 
> It is working in 1.20.4 now, but it is incompatible with other versions. Could you please make other versions like that?

which version do you need?

**Comment by Young912** [comment]
> > > can you test this dev build?
> > > https://github.com/sebseb7/autotrade-fabric/actions/runs/7326365773
> > 
> > 
> > It is working in 1.20.4 now, but it is incompatible with other versions. Could you please make other versions like that?
> 
> which version do you need?

1.20.1

**Comment by sebseb7** [comment]
> 1.20.1

try this:

https://github.com/sebseb7/autotrade-fabric/actions/runs/7330223253

**Comment by Young912** [comment]
> > 1.20.1
> 
> try this:
> 
> https://github.com/sebseb7/autotrade-fabric/actions/runs/7330223253

![1](https://github.com/sebseb7/autotrade-fabric/assets/43774123/96677377-7f4c-4520-855e-1196261533e9)
Something goes wrong

**Comment by Young912** [comment]
> > 1.20.1
> 
> try this:
> 
> https://github.com/sebseb7/autotrade-fabric/actions/runs/7330223253

Thank you very much!

**Comment by Young912** [comment]
Hi, can you add the features I mentioned earlier in your mod v0.0.10, the minecraft v1.20.1. Thank you again!

**Comment by sebseb7** [comment]
https://modrinth.com/mod/autotrade-fabric/version/e79PzG6A
